/**
 * app_ai_display.c
 *
 * Runs ST.AI inference on the STM32N6 NPU and displays the 96×96 generated
 * image centred on the MB1860A 800×480 LTDC display.
 *
 * Memory map assumptions (set by FSBL before jumping here):
 *   0x70100000  Application code  (XIP from NOR Flash via XSPI1)
 *   0x71000000  network_data.bin  (12 MB weights, memory-mapped Flash)
 *   0x90000000  PSRAM 32 MB       (APS256XXN-OBR via XSPI2)
 *
 * PSRAM layout used here:
 *   0x90000000  activations       (7 373 408 bytes, ~7.04 MB)
 *   0x90720000  output buffer     (  110 592 bytes, ~108 KB)
 *   0x9073B000  fb0 RGB565        (  768 000 bytes, 800×480×2)
 *   0x907FB000  fb1 RGB565        (  768 000 bytes, double-buffer spare)
 */

#include "app_ai_display.h"
#include "network.h"      /* generated by stedgeai */
#include "stai.h"         /* ST.AI runtime API     */

/* BSP drivers for STM32N6570-DK */
#include "stm32n6570_discovery_lcd.h"
#include "stm32n6570_discovery_xspi.h"  /* BSP_XSPI_RAM_Init/EnableMemoryMapped */

#include <string.h>
#include <math.h>         /* fabsf */

/* ── PSRAM section attribute (matched to linker script .psram_section) ── */
#define PSRAM_SECTION __attribute__((section(".psram_bss"))) __attribute__((aligned(32)))

/* ── Static buffers in PSRAM ──────────────────────────────────── */
PSRAM_SECTION static uint8_t  s_activations[NET_ACT_SIZE];
PSRAM_SECTION static float    s_output[1 * 3 * APP_IMG_H * APP_IMG_W];
PSRAM_SECTION static uint16_t s_framebuffer[DISPLAY_W * DISPLAY_H];

/* ── Small buffers on AXISRAM (fast, close to NPU) ───────────── */
static int8_t s_input_z  [NET_IN1_SIZE] __attribute__((aligned(4)));
static int8_t s_input_emb[NET_IN2_SIZE] __attribute__((aligned(4)));

/* ── Network context (opaque, ~100 bytes) ─────────────────────── */
static _stai_network_context s_net_ctx;

/* ── Weights are memory-mapped from Flash ─────────────────────── */
#define WEIGHTS_FLASH_ADDR  0x71000000UL

/* ── Simple XorShift-32 PRNG ──────────────────────────────────── */
static uint32_t s_rng_state = 0xDEADBEEFUL;
static uint32_t xorshift32(void)
{
    uint32_t x = s_rng_state;
    x ^= x << 13;
    x ^= x >> 17;
    x ^= x << 5;
    s_rng_state = x;
    return x;
}

/**
 * Box-Muller: returns one standard-normal float using two uniform samples.
 * Consumes two xorshift32() calls.
 */
static float randn(void)
{
    /* Uniform (0,1] from two 32-bit words */
    float u1 = (float)(xorshift32() >> 1) / (float)(1UL << 31) + 1e-7f;
    float u2 = (float)(xorshift32() >> 1) / (float)(1UL << 31) * 6.2831853f;
    /* Approximation: use only the magnitude, sign toggled by LSB of u2 bits */
    float mag = sqrtf(-2.0f * logf(u1));
    return mag * cosf(u2);
}

/* ── Saturating float→INT8 ───────────────────────────────────── */
static inline int8_t float_to_int8(float v)
{
    int32_t i = (int32_t)(v + (v >= 0.0f ? 0.5f : -0.5f));
    if (i >  127) return  127;
    if (i < -128) return -128;
    return (int8_t)i;
}

/* ── Fill z with quantised Gaussian noise ────────────────────── */
static void fill_z_noise(void)
{
    for (int i = 0; i < NET_IN1_SIZE; i++) {
        float z_f = randn() * CST_GAUSSIAN_PRIOR;   /* N(0, 0.8) */
        s_input_z[i] = float_to_int8(z_f / Z_SCALE);
    }
}

/* ── Convert NCHW float32[1,3,H,W] to RGB565 in-place ──────── */
static void float_nchw_to_rgb565(const float *src,
                                  uint16_t    *dst,
                                  int H, int W)
{
    int pixels = H * W;
    for (int p = 0; p < pixels; p++) {
        /* src layout: [R_plane][G_plane][B_plane] */
        float rf = src[0 * pixels + p];
        float gf = src[1 * pixels + p];
        float bf = src[2 * pixels + p];

        /* Tanh output is in [-1, 1]; map to [0, 255] */
        uint8_t r = (uint8_t)((rf + 1.0f) * 127.5f + 0.5f);
        uint8_t g = (uint8_t)((gf + 1.0f) * 127.5f + 0.5f);
        uint8_t b = (uint8_t)((bf + 1.0f) * 127.5f + 0.5f);

        /* Clip */
        if (rf < -1.0f) r = 0;   else if (rf > 1.0f) r = 255;
        if (gf < -1.0f) g = 0;   else if (gf > 1.0f) g = 255;
        if (bf < -1.0f) b = 0;   else if (bf > 1.0f) b = 255;

        /* Pack RGB565: R[7:3] G[7:2] B[7:3] */
        dst[p] = (uint16_t)(((r & 0xF8u) << 8) |
                             ((g & 0xFCu) << 3) |
                             ((b & 0xF8u) >> 3));
    }
}

/* ── Paint the 96×96 RGB565 tile centred on the panel ─────────── */
static void display_tile(const uint16_t *rgb565)
{
    BSP_LCD_FillRGBRect(0,                      /* instance 0 */
                        (uint8_t *)rgb565,
                        DISPLAY_X_OFFSET,
                        DISPLAY_Y_OFFSET,
                        APP_IMG_W,
                        APP_IMG_H);
    BSP_LCD_Reload(0, BSP_LCD_RELOAD_IMMEDIATE);
}

/* ═══════════════════════════════════════════════════════════════ */
/*  Public API                                                     */
/* ═══════════════════════════════════════════════════════════════ */

void App_AI_Display_Init(void)
{
    /* ── 0. Initialise external PSRAM via BSP ──────────────────── */
    /* The XIP FSBL only configures NOR Flash (XSPI2).  PSRAM (XSPI1)
     * must be initialised by the application before any PSRAM access. */
    if (BSP_XSPI_RAM_Init(0) != BSP_ERROR_NONE) {
        while (1);  /* PSRAM init failure — check board power / XSPI1 clock */
    }
    if (BSP_XSPI_RAM_EnableMemoryMappedMode(0) != BSP_ERROR_NONE) {
        while (1);
    }

    /* ── 1. Enable NPU SRAM clocks (required for atonn runtime) ── */
    __HAL_RCC_AXISRAM3_MEM_CLK_ENABLE();
    __HAL_RCC_AXISRAM4_MEM_CLK_ENABLE();
    __HAL_RCC_AXISRAM5_MEM_CLK_ENABLE();
    __HAL_RCC_AXISRAM6_MEM_CLK_ENABLE();
    __HAL_RCC_NPU_CLK_ENABLE();

    /* ── 2. Initialise display ─────────────────────────────────── */
    BSP_LCD_Init(0, LCD_ORIENTATION_LANDSCAPE);
    BSP_LCD_SetActiveLayer(0, 0);

    /* Clear framebuffer to black */
    memset(s_framebuffer, 0, sizeof(s_framebuffer));
    BSP_LCD_SetLayerAddress(0, 0, (uint32_t)s_framebuffer);
    BSP_LCD_Reload(0, BSP_LCD_RELOAD_IMMEDIATE);

    /* ── 3. Initialise ST.AI network context ───────────────────── */
    stai_return_code rc = stai_network_init((stai_network *)&s_net_ctx);
    if (rc != STAI_SUCCESS) {
        /* Halt — context init failure is unrecoverable */
        while (1);
    }

    /* ── 4. Bind weights (memory-mapped from Flash) ────────────── */
    const stai_ptr weights[STAI_NETWORK_WEIGHTS_NUM] = {
        (stai_ptr)WEIGHTS_FLASH_ADDR
    };
    stai_network_set_weights((stai_network *)&s_net_ctx, weights,
                             STAI_NETWORK_WEIGHTS_NUM);

    /* ── 5. Bind activation scratch in PSRAM ──────────────────── */
    stai_ptr acts[STAI_NETWORK_ACTIVATIONS_NUM] = {
        (stai_ptr)s_activations
    };
    stai_network_set_activations((stai_network *)&s_net_ctx, acts,
                                 STAI_NETWORK_ACTIVATIONS_NUM);

    /* ── 6. Bind input / output buffers ───────────────────────── */
    stai_ptr inputs[STAI_NETWORK_IN_NUM] = {
        (stai_ptr)s_input_z,
        (stai_ptr)s_input_emb
    };
    stai_network_set_inputs((stai_network *)&s_net_ctx, inputs,
                            STAI_NETWORK_IN_NUM);

    stai_ptr outputs[STAI_NETWORK_OUT_NUM] = {
        (stai_ptr)s_output
    };
    stai_network_set_outputs((stai_network *)&s_net_ctx, outputs,
                             STAI_NETWORK_OUT_NUM);

    /* ── 7. Zero the text embedding (unconditional generation) ─── */
    memset(s_input_emb, 0, NET_IN2_SIZE);
}

void App_AI_Display_Run(void)
{
    /* Fresh random latent z ~ N(0, CST_GAUSSIAN_PRIOR) quantised to INT8 */
    fill_z_noise();

    /* Run inference (synchronous / blocking) */
    stai_return_code rc = stai_network_run((stai_network *)&s_net_ctx,
                                           STAI_MODE_SYNC);
    if (rc != STAI_SUCCESS) {
        /* On error: fill tile with red to signal failure, then continue */
        for (int i = 0; i < APP_IMG_W * APP_IMG_H; i++) {
            s_framebuffer[DISPLAY_Y_OFFSET * DISPLAY_W
                          + DISPLAY_X_OFFSET + i] = 0xF800u; /* RED in RGB565 */
        }
        BSP_LCD_Reload(0, BSP_LCD_RELOAD_IMMEDIATE);
        return;
    }

    /* Convert NCHW float32 output → RGB565 tile */
    uint16_t tile[APP_IMG_W * APP_IMG_H];
    float_nchw_to_rgb565(s_output, tile, APP_IMG_H, APP_IMG_W);

    /* Paint centred tile on the 800×480 panel */
    display_tile(tile);
}
